# Generated by Django 4.0.5 on 2022-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgeducatuion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='orgeducatuion',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес сайта'),
        ),
    ]
