# Generated by Django 4.0.5 on 2022-09-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ok',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Одноклассники'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='telegtam',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='viber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vk',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ВКонтакте'),
        ),
    ]
