# Generated by Django 4.1 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgEducatuion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_org', models.CharField(max_length=100, verbose_name='Название')),
                ('description_org', models.TextField(verbose_name='Описание')),
                ('address_org', models.CharField(max_length=256, verbose_name='Адрес')),
                ('phone_org', models.CharField(max_length=15, verbose_name='Телефон')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
