# Generated by Django 4.1 on 2022-10-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_orgeducatuion_alter_organization_publication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgeducatuion',
            table='org_education',
        ),
    ]
