# Generated by Django 4.0.5 on 2022-09-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organization_instagram_alter_organization_ok_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.SlugField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=150, verbose_name='Название')),
                ('description_class', models.TextField(verbose_name='Описание')),
                ('address_class', models.CharField(max_length=256, verbose_name='Адрес')),
                ('datatime_class', models.CharField(max_length=256, verbose_name='Время проведения')),
                ('age_class', models.CharField(max_length=100, verbose_name='Для кого')),
                ('price_class', models.CharField(max_length=50, verbose_name='Цена')),
                ('phone_reference', models.CharField(max_length=15, verbose_name='Телефон')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.category')),
                ('name_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_photo', models.CharField(max_length=100)),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=3, verbose_name='Возраст')),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
            ],
            options={
                'db_table': 'age',
            },
        ),
    ]
