# Generated by Django 4.1 on 2022-10-11 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_option', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'age_list',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_class', models.CharField(max_length=150, verbose_name='Название')),
                ('description_class', models.TextField(verbose_name='Описание')),
                ('address_class', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес')),
                ('datatime_class', models.CharField(blank=True, max_length=256, null=True, verbose_name='Время проведения')),
                ('age_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Для кого')),
                ('price_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена')),
                ('phone_reference', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Имя файла')),
                ('created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('publication', models.BooleanField(default=False, verbose_name='Публикация')),
                ('name_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.category', verbose_name='Категория')),
                ('name_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Название организации')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_photo', models.ImageField(upload_to='logo/', verbose_name='Имя файла')),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Название занятия')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.age_list', verbose_name='Название занятия')),
                ('name_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Название занятия')),
            ],
            options={
                'db_table': 'age',
            },
        ),
    ]
