# Generated by Django 4.0.5 on 2022-09-15 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_alter_organization_instagram_alter_organization_ok_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=250, verbose_name='Название')),
                ('description_event', models.TextField(verbose_name='Описание')),
                ('address_event', models.CharField(max_length=256, verbose_name='Адрес')),
                ('date_event', models.DateField(verbose_name='Дата проведения')),
                ('time_event', models.TimeField(verbose_name='Время проведения')),
                ('age_event', models.CharField(max_length=250, verbose_name='Для кого')),
                ('price_event', models.CharField(max_length=250, verbose_name='Цена')),
                ('price_reference', models.TextField(verbose_name='как купить')),
                ('phone_reference', models.CharField(max_length=15, verbose_name='Телефон')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('name_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
