# Generated by Django 4.1 on 2022-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Афиша'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publication',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
